server:
  port: 3344
spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangchunfeng/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 192.168.1.238
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
