server:
  port: 84
spring:
  application:
    name: cloudalibaba-consumer-order84
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719


service-url: http://cloudalibaba-provider-payment

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
